"""
Auto-generated seed script containing a dump of the current database.
Run with: python seed.py
"""

import os
import sys
import datetime

sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, os.path.dirname(__file__))

from app.database import SessionLocal, Base, engine
from app.models import User, Chapter, File, FileVersion
from app.domains.projects.models import Project, ProjectStylesheet
from app.domains.clients.models import Client
from app.domains.workflow.models import RolesMaster, StageMaster, StageDetail, WorkflowMaster, ChapterInfo

def create_tables():
    Base.metadata.create_all(bind=engine)

DUMPED_DATA = {
    'User': [
        {'id': 1, 'username': 'admin', 'email': 'admin@example.com', 'password': 'Admin@1234', 'is_active': True, 'role': 'admin', 'team': 'Admin Team', 'customer_access': None},
        {'id': 12, 'username': 'Murali', 'email': 'Muraliba@s4carlisle.com', 'password': 'Admin@1234', 'is_active': True, 'role': 'admin', 'team': 'Admin Team', 'customer_access': None},
        {'id': 2, 'username': 'admin_hema', 'email': 'hema.admin@wms.com', 'password': 'Admin@1234', 'is_active': True, 'role': 'admin', 'team': 'IT', 'customer_access': None},
    ],
    'Client': [
        {'id': 1, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Gavin', 'surname': 'Jamieson', 'name_company': 'Artech House', 'company': 'Artech House', 'division': 'AHUS001', 'designation': 'Senior Commissioning Editor', 'department': None, 'email': 'gjamieson@artechhouse.co.uk', 'website': None, 'vendor_number': None, 'address1': '16 Sussex Street', 'address2': None, 'city': 'London', 'state': None, 'country': 'UK', 'zip_code': 'SW1V4RW', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': '+44(0)20 7596 8751', 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Artech_House.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 2, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Mary', 'surname': 'Sanger', 'name_company': 'Aspen Publishing', 'company': 'Aspen Publishing', 'division': 'ASPEN0503', 'designation': None, 'department': None, 'email': 'mary.sanger@aspenpublishing.com', 'website': None, 'vendor_number': None, 'address1': '1 Wall Street, Suite 302', 'address2': None, 'city': 'Burlington', 'state': None, 'country': 'US', 'zip_code': None, 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Aspen_Publishing.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 3, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Jolien', 'surname': 'Honings', 'name_company': 'Boom uitgevers Den Haag', 'company': 'Boom uitgevers Den Haag', 'division': 'ELPUB0504', 'designation': None, 'department': None, 'email': 'J.Honings@boom.nl', 'website': None, 'vendor_number': None, 'address1': 'Kanonstraat 4-IV, 2508 CG DEN HAAG', 'address2': None, 'city': None, 'state': None, 'country': 'The Netherlands', 'zip_code': None, 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Boom_uitgevers_Den_Haag.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 4, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Charlene', 'surname': 'Kronstedt', 'name_company': 'Business Expert Press', 'company': 'Business Expert Press', 'division': 'BEP001', 'designation': None, 'department': None, 'email': 'charlene.kronstedt@businessexpertpress.com', 'website': 'www.businessexpertpress.com', 'vendor_number': None, 'address1': None, 'address2': None, 'city': None, 'state': None, 'country': None, 'zip_code': None, 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Business_Expert_Press.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 5, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Jeremy', 'surname': 'Boehme', 'name_company': 'Common Ground Research Networks', 'company': 'Common Ground Research Networks', 'division': 'CGRN 001', 'designation': None, 'department': None, 'email': 'jeremy.boehme@cgnetworks.org', 'website': None, 'vendor_number': None, 'address1': 'University of Illinois Research Park, 2001 South First Street, Suite 202', 'address2': None, 'city': 'Champaign', 'state': None, 'country': 'US', 'zip_code': 'IL 61820', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': '1-217-328-0405', 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Common_Ground_Research_Networks.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 6, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Melissa', 'surname': 'Zavala', 'name_company': 'Human Kinetics', 'company': 'Human Kinetics', 'division': 'HK0001', 'designation': None, 'department': None, 'email': 'MelissaZ@hkusa.com', 'website': 'US.HumanKinetics.com', 'vendor_number': None, 'address1': '1607 N. Market Street', 'address2': None, 'city': 'Champaign', 'state': None, 'country': 'US', 'zip_code': 'IL  61820', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Human_Kinetics.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 7, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Kristen', 'surname': 'Rogers', 'name_company': 'Jones & Bartlett Learning', 'company': 'Jones & Bartlett Learning', 'division': 'JBL001', 'designation': None, 'department': None, 'email': 'Kristen.Rogers@ascendlearning.com', 'website': 'http://www.jblearning.com', 'vendor_number': None, 'address1': '5 Wall Street', 'address2': None, 'city': 'Burlington', 'state': None, 'country': 'US', 'zip_code': 'MA 01803', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': '978-443-5000', 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Jones___Bartlett_Learning.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 8, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Cari', 'surname': 'Rieckens', 'name_company': 'Kendall Hunt Publishing', 'company': 'Kendall Hunt Publishing', 'division': 'KENIA010', 'designation': None, 'department': None, 'email': 'CRieckens@kendallhunt.com', 'website': None, 'vendor_number': None, 'address1': '4050 Westmark Drive', 'address2': None, 'city': 'Dubuque', 'state': None, 'country': 'US', 'zip_code': None, 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Kendall_Hunt_Publishing.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 9, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'David', 'surname': 'Hawkins', 'name_company': 'Pelagic Publishing - The Exeter Press Limited', 'company': 'Pelagic Publishing - The Exeter Press Limited', 'division': 'EP001', 'designation': None, 'department': None, 'email': 'davidhawkins@pelagicpublishing.com', 'website': None, 'vendor_number': None, 'address1': 'PO Box 874, Exeter, EX3 9BR', 'address2': None, 'city': None, 'state': None, 'country': 'UK', 'zip_code': None, 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Pelagic_Publishing_-_The_Exeter_Press_Limited.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 10, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Kris', 'surname': 'Parrish', 'name_company': 'Springer Publishing Company', 'company': 'Springer Publishing Company', 'division': 'SPRNY00', 'designation': None, 'department': None, 'email': 'kparrish@springerpub.com', 'website': None, 'vendor_number': None, 'address1': '11 West 42nd Street', 'address2': None, 'city': None, 'state': None, 'country': 'US', 'zip_code': 'NY 10036', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Springer_Publishing_Company.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 11, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Kelly', 'surname': 'Bowman', 'name_company': 'Wolters Kluwer Health', 'company': 'Wolters Kluwer Health', 'division': 'KLUPA02', 'designation': None, 'department': None, 'email': 'K.Heaney@wolterskluwer.com', 'website': None, 'vendor_number': None, 'address1': 'One Commerce Square, 2005 Market Street, Suite 350', 'address2': None, 'city': 'Philadelphia', 'state': None, 'country': 'US', 'zip_code': 'PA 19103', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Wolters_Kluwer_Health.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 12, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Julie', 'surname': None, 'name_company': 'Penn State University Press', 'company': 'Penn State University Press', 'division': 'PEUPPE1', 'designation': None, 'department': None, 'email': 'jas1035@psu.edu', 'website': None, 'vendor_number': None, 'address1': '8 University Dr., USB 1, Ste. C University Park,', 'address2': None, 'city': None, 'state': None, 'country': 'US', 'zip_code': 'PA 16802-1003', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 13, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Valeria', 'surname': 'Ceci', 'name_company': 'Mattioli 1885', 'company': 'Mattioli 1885', 'division': 'MAT001', 'designation': None, 'department': None, 'email': 'valeriaceci@mattiolihealth.com', 'website': None, 'vendor_number': None, 'address1': 'strada della Lodesana 649/sx, 43036 Fidenza (Parma)', 'address2': None, 'city': None, 'state': None, 'country': 'Italy', 'zip_code': None, 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Mattioli 1885.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 14, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Victoria', 'surname': 'Putman', 'name_company': 'Putman Productions', 'company': 'Putman Productions', 'division': 'PUBI001', 'designation': None, 'department': None, 'email': 'VictoriaPutman@PutmanBookServices.com', 'website': None, 'vendor_number': None, 'address1': 'PO Box 85', 'address2': None, 'city': 'Bellevue', 'state': None, 'country': 'US', 'zip_code': 'IA 52031', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 15, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Robert', 'surname': 'Tamplin', 'name_company': 'Henry Stewart Publications LLP', 'company': 'Henry Stewart Publications LLP', 'division': 'HSP002', 'designation': None, 'department': None, 'email': 'Robert@hspublications.co.uk', 'website': None, 'vendor_number': None, 'address1': 'c/o TC Citroen Wells Ltd, 5th Floor, 3 Dorset Rise,', 'address2': None, 'city': None, 'state': None, 'country': 'UK', 'zip_code': 'EC4 Y8E', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Henry Stewart Publications LLP.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 16, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Claire', 'surname': 'Gough', 'name_company': 'Authentic Media', 'company': 'Authentic Media', 'division': 'AUM001', 'designation': None, 'department': None, 'email': 'claire.gough@authenticmedia.co.uk', 'website': None, 'vendor_number': None, 'address1': 'PO Box 6326, Bletchley, Milton Keynes', 'address2': None, 'city': None, 'state': None, 'country': 'UK', 'zip_code': 'MK1 9GG', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Authentic Media.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 17, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': None, 'surname': None, 'name_company': 'FA Davis Publishing', 'company': 'FA Davis Publishing', 'division': 'FADPA01', 'designation': None, 'department': None, 'email': 'contact@fadavispublishing.com', 'website': None, 'vendor_number': None, 'address1': '1915 Arch Street', 'address2': None, 'city': 'Philadelphia', 'state': None, 'country': 'US', 'zip_code': 'PA 19103', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/FA Davis Publishing.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 18, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Jenny', 'surname': 'Corriveau', 'name_company': 'Goodheart-Willcox Publisher', 'company': 'Goodheart-Willcox Publisher', 'division': 'GWP000', 'designation': None, 'department': None, 'email': 'jcorriveau@g-w.com', 'website': None, 'vendor_number': None, 'address1': '18604 West Creek Drive Tinley Park', 'address2': None, 'city': None, 'state': None, 'country': 'US', 'zip_code': 'IL 60477', 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'logo_url': '/logos/Goodheart-Willcox Publisher.png', 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 19, 'category_type': 'Organization', 'contact_type': 'Customer', 'first_name': 'Vijay', 'surname': 'Jain', 'name_company': 'Jain Vishva Bharati', 'company': 'Jain Vishva Bharati', 'division': 'JVB001', 'designation': None, 'department': None, 'email': 'contact@jainvishvabharati.org', 'website': None, 'vendor_number': None, 'address1': None, 'address2': None, 'city': None, 'state': None, 'country': None, 'zip_code': None, 'sub_specialisation': None, 'working_hours': None, 'contact_hours': None, 'phone_main': None, 'phone_additional': None, 'active_status': True, 'created_by': None, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
    ],
    'RolesMaster': [
        # Project Management Team
        {'id': 1,  'role_name': 'Asst General Manager',       'team': 'Project Management Team', 'description': None, 'active_status': True},
        {'id': 2,  'role_name': 'Senior Project Manager',     'team': 'Project Management Team', 'description': None, 'active_status': True},
        {'id': 3,  'role_name': 'Project Manager',            'team': 'Project Management Team', 'description': None, 'active_status': True},
        {'id': 4,  'role_name': 'Manuscript Analysis Operator', 'team': 'Project Management Team', 'description': None, 'active_status': True},
        # Editorial Team
        {'id': 5,  'role_name': 'Editorial Manager',          'team': 'Editorial Team', 'description': None, 'active_status': True},
        {'id': 6,  'role_name': 'Team Lead - Editorial',      'team': 'Editorial Team', 'description': None, 'active_status': True},
        {'id': 7,  'role_name': 'Copyeditor',                 'team': 'Editorial Team', 'description': None, 'active_status': True},
        {'id': 8,  'role_name': 'Technical Editor',           'team': 'Editorial Team', 'description': None, 'active_status': True},
        {'id': 9,  'role_name': 'Pre Editor',                 'team': 'Editorial Team', 'description': None, 'active_status': True},
        # Production Team
        {'id': 10, 'role_name': 'Production Manager',         'team': 'Production Team', 'description': None, 'active_status': True},
        {'id': 11, 'role_name': 'Team Lead - Production',     'team': 'Production Team', 'description': None, 'active_status': True},
        {'id': 12, 'role_name': 'Senior Compositor',          'team': 'Production Team', 'description': None, 'active_status': True},
        {'id': 13, 'role_name': 'Compositor',                 'team': 'Production Team', 'description': None, 'active_status': True},
        {'id': 14, 'role_name': 'Senior Quality Controller',  'team': 'Production Team', 'description': None, 'active_status': True},
        {'id': 15, 'role_name': 'Quality Controller',         'team': 'Production Team', 'description': None, 'active_status': True},
        # Template Team
        {'id': 16, 'role_name': 'Template Team Manager',      'team': 'Template Team', 'description': None, 'active_status': True},
        {'id': 17, 'role_name': 'Template Designer',          'team': 'Template Team', 'description': None, 'active_status': True},
        # Graphics Team
        {'id': 18, 'role_name': 'Graphics Manager',           'team': 'Graphics Team', 'description': None, 'active_status': True},
        {'id': 19, 'role_name': 'Senior Graphics Designer',   'team': 'Graphics Team', 'description': None, 'active_status': True},
        {'id': 20, 'role_name': 'Graphics Designer',          'team': 'Graphics Team', 'description': None, 'active_status': True},
        # XML Conversion Team
        {'id': 21, 'role_name': 'XML Manager',                'team': 'XML Conversion Team', 'description': None, 'active_status': True},
        {'id': 22, 'role_name': 'Senior XML Operator',        'team': 'XML Conversion Team', 'description': None, 'active_status': True},
        {'id': 23, 'role_name': 'XML Operator',               'team': 'XML Conversion Team', 'description': None, 'active_status': True},
        # Non-XML Conversion Team
        {'id': 24, 'role_name': 'Non-XML Manager',            'team': 'Non-XML Conversion Team', 'description': None, 'active_status': True},
        {'id': 25, 'role_name': 'Senior Non-XML Operator',    'team': 'Non-XML Conversion Team', 'description': None, 'active_status': True},
        {'id': 26, 'role_name': 'Non-XML Operator',           'team': 'Non-XML Conversion Team', 'description': None, 'active_status': True},
        # Accessibility Team
        {'id': 27, 'role_name': 'Team Lead - Accessibility',  'team': 'Accessibility Team', 'description': None, 'active_status': True},
        {'id': 28, 'role_name': 'Accessibility Specialist',   'team': 'Accessibility Team', 'description': None, 'active_status': True},
        # Index Team
        {'id': 29, 'role_name': 'Index Manager',              'team': 'Index Team', 'description': None, 'active_status': True},
        {'id': 30, 'role_name': 'Index Operator',             'team': 'Index Team', 'description': None, 'active_status': True},
        # Admin Team
        {'id': 31, 'role_name': 'Admin', 'team': 'Admin Team', 'description': None, 'active_status': True},
        # Publishing Team
        {'id': 32, 'role_name': 'Publisher', 'team': 'Publishing Team', 'description': None, 'active_status': True},
        # Author Team
        {'id': 33, 'role_name': 'Author', 'team': 'Author Team', 'description': None, 'active_status': True},
    ],
    'StageMaster': [
        {'id': 1, 'stage_name': 'Job Initiation', 'description': 'Receive Job', 'sla_level1': 1, 'sla_level2': 1, 'sla_level3': 1, 'roles': ['Project Manager', 'Manuscript Analysis Operator'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 2, 'stage_name': 'Manuscript Analysis', 'description': 'Receive manuscript, analyze structure, assess complexity and assign project resources.', 'sla_level1': 1, 'sla_level2': 2, 'sla_level3': 3, 'roles': ['Project Manager', 'Manuscript Analysis Operator'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 3, 'stage_name': 'Editorial Assessment', 'description': 'Review manuscript completeness, quality and identify editorial issues.', 'sla_level1': 1, 'sla_level2': 2, 'sla_level3': 3, 'roles': ['Editorial Manager', 'Team Lead - Editorial'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 4, 'stage_name': 'Pre-editing', 'description': 'Review manuscript structure and prepare content for editing.', 'sla_level1': 2, 'sla_level2': 3, 'sla_level3': 5, 'roles': ['Team Lead - Editorial', 'Pre Editor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 5, 'stage_name': 'Copyediting', 'description': 'Apply language edits, style compliance and prepare author queries.', 'sla_level1': 5, 'sla_level2': 7, 'sla_level3': 10, 'roles': ['Team Lead - Editorial', 'Copyeditor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 6, 'stage_name': 'AQ Resolution', 'description': 'Resolve author queries and review approved changes.', 'sla_level1': 2, 'sla_level2': 3, 'sla_level3': 5, 'roles': ['Project Manager', 'Copyeditor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 7, 'stage_name': 'Technical Editing', 'description': 'Validate references, terminology and cross references.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['Technical Editor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 8, 'stage_name': 'Template Processing', 'description': 'Create and validate templates for production workflow.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['Template Team Manager', 'Template Designer'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 9, 'stage_name': 'Art Processing', 'description': 'Process and quality check figures and artwork.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['Graphics Manager', 'Graphics Designer'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 10, 'stage_name': 'Non-XML Processing', 'description': 'Prepare and validate non-XML deliverables.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['Non-XML Manager', 'Non-XML Operator'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 11, 'stage_name': 'Typesetting', 'description': 'Generate layouts and first proof output.', 'sla_level1': 5, 'sla_level2': 7, 'sla_level3': 10, 'roles': ['Production Manager', 'Senior Compositor', 'Compositor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 12, 'stage_name': 'Proofreading', 'description': 'Review proofs and identify corrections.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['Quality Controller', 'Senior Quality Controller'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 13, 'stage_name': 'Indexing', 'description': 'Create, review and finalize index content.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['Index Manager', 'Index Operator'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 14, 'stage_name': 'Corrections & 2P', 'description': 'Apply corrections and generate second proof.', 'sla_level1': 2, 'sla_level2': 3, 'sla_level3': 5, 'roles': ['Compositor', 'Senior Quality Controller'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 15, 'stage_name': 'QC & Pre-flight', 'description': 'Perform final QC, validation and accessibility checks.', 'sla_level1': 1, 'sla_level2': 2, 'sla_level3': 3, 'roles': ['Senior Quality Controller', 'Quality Controller'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 16, 'stage_name': 'Delivery', 'description': 'Deliver final files and archive project assets.', 'sla_level1': 1, 'sla_level2': 1, 'sla_level3': 2, 'roles': ['Project Manager'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 17, 'stage_name': 'Reprint', 'description': 'Handle reprint requests and errata corrections.', 'sla_level1': 1, 'sla_level2': 2, 'sla_level3': 3, 'roles': ['Project Manager', 'Compositor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 18, 'stage_name': 'XML Conversion', 'description': 'Convert content to XML and perform schema validation.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['XML Manager', 'Senior XML Operator'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 19, 'stage_name': 'Digital Processing', 'description': 'Prepare content for digital delivery platforms.', 'sla_level1': 2, 'sla_level2': 3, 'sla_level3': 5, 'roles': ['XML Manager', 'Non-XML Manager'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 20, 'stage_name': 'Accessibility', 'description': 'Apply accessibility remediation and tagging.', 'sla_level1': 3, 'sla_level2': 5, 'sla_level3': 7, 'roles': ['Accessibility Specialist'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 21, 'stage_name': 'Accessibility QC', 'description': 'Validate accessibility compliance and certification.', 'sla_level1': 1, 'sla_level2': 2, 'sla_level3': 3, 'roles': ['Senior Quality Controller', 'Accessibility Specialist'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 22, 'stage_name': 'Publisher Review', 'description': 'Resolve author queries and review approved changes.', 'sla_level1': 2, 'sla_level2': 3, 'sla_level3': 5, 'roles': ['Project Manager', 'Copyeditor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 23, 'stage_name': 'Author Review', 'description': 'Resolve author queries and review approved changes.', 'sla_level1': 2, 'sla_level2': 3, 'sla_level3': 5, 'roles': ['Project Manager', 'Copyeditor'], 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

    ],
    'WorkflowMaster': [
        {'id': 1, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 2, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Editorial Assessment', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 3, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Editorial Assessment', 'previous_stage': 'Job Initiation', 'next_stage': 'Template Processing', 'description': 'Stage Editorial Assessment for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 4, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Template Processing', 'previous_stage': 'Editorial Assessment', 'next_stage': 'Art Processing', 'description': 'Stage Template Processing for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 5, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Art Processing', 'previous_stage': 'Template Processing', 'next_stage': 'Pre-editing', 'description': 'Stage Art Processing for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 6, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Pre-editing', 'previous_stage': 'Art Processing', 'next_stage': 'Copyediting', 'description': 'Stage Pre-editing for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 7, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Copyediting', 'previous_stage': 'Pre-editing', 'next_stage': 'AQ Resolution', 'description': 'Stage Copyediting for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 8, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'AQ Resolution', 'previous_stage': 'Copyediting', 'next_stage': 'Non-XML Processing', 'description': 'Stage AQ Resolution for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 9, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Non-XML Processing', 'previous_stage': 'AQ Resolution', 'next_stage': 'Typesetting', 'description': 'Stage Non-XML Processing for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 10, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Typesetting', 'previous_stage': 'Non-XML Processing', 'next_stage': 'Proofreading', 'description': 'Stage Typesetting for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 11, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Proofreading', 'previous_stage': 'Typesetting', 'next_stage': 'Indexing', 'description': 'Stage Proofreading for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 12, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Indexing', 'previous_stage': 'Proofreading', 'next_stage': 'Corrections & 2P', 'description': 'Stage Indexing for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 13, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Corrections & 2P', 'previous_stage': 'Indexing', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Corrections & 2P for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 14, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Corrections & 2P', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 15, 'workflow_name': 'WF-01 Fresh Book', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        
        
        {'id': 16, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 17, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Manuscript Analysis', 'previous_stage': "Job Initiation", 'next_stage': 'Reprint', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 18, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Reprint', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Template Processing', 'description': 'Stage Reprint for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 19, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Template Processing', 'previous_stage': 'Reprint', 'next_stage': 'Art Processing', 'description': 'Stage Template Processing for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 20, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Art Processing', 'previous_stage': 'Template Processing', 'next_stage': 'Corrections & 2P', 'description': 'Stage Art Processing for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 21, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Corrections & 2P', 'previous_stage': 'Art Processing', 'next_stage': 'Proofreading', 'description': 'Stage Reprint for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 22, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Proofreading', 'previous_stage': 'Corrections & 2P', 'next_stage': 'Publisher Review', 'description': 'Stage Reprint for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 23, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Publisher Review', 'previous_stage': 'Proofreading', 'next_stage': 'Delivery', 'description': 'Stage Reprint for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 24, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Publisher Review', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-01 Fresh Book.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 25, 'workflow_name': 'WF-02 Reprint', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-02 Reprint.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 26, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 27, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Template Processing', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 28, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Template Processing', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Copyediting', 'description': 'Stage Template Processing for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 29, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Copyediting', 'previous_stage': 'Template Processing', 'next_stage': 'AQ Resolution', 'description': 'Stage Copyediting for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 30, 'workflow_name': 'WF-03 Revision', 'stage_name': 'AQ Resolution', 'previous_stage': 'Copyediting', 'next_stage': 'Typesetting', 'description': 'Stage AQ Resolution for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 31, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Typesetting', 'previous_stage': 'AQ Resolution', 'next_stage': 'Art Processing', 'description': 'Stage Typesetting for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 32, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Art Processing', 'previous_stage': 'Typesetting', 'next_stage': 'Proofreading', 'description': 'Stage Art Processing for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 33, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Proofreading', 'previous_stage': 'Art Processing', 'next_stage': 'Corrections & 2P', 'description': 'Stage Proofreading for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 34, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Corrections & 2P', 'previous_stage': 'Proofreading', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Corrections & 2P for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 35, 'workflow_name': 'WF-03 Revision', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Corrections & 2P', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 36, 'workflow_name': 'WF-03 Revision', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-03 Revision.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 37, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 38, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Editorial Assessment', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 39, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'Editorial Assessment', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Copyediting', 'description': 'Stage Editorial Assessment for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 40, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'Copyediting', 'previous_stage': 'Editorial Assessment', 'next_stage': 'Technical Editing', 'description': 'Stage Copyediting for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 41, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'Technical Editing', 'previous_stage': 'Copyediting', 'next_stage': 'AQ Resolution', 'description': 'Stage Technical Editing for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 42, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'AQ Resolution', 'previous_stage': 'Technical Editing', 'next_stage': 'QC & Pre-flight', 'description': 'Stage AQ Resolution for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 43, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'AQ Resolution', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 44, 'workflow_name': 'WF-04 Copyediting Only', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-04 Copyediting Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 45, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 46, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Template Processing', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 47, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Template Processing', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Art Processing', 'description': 'Stage Template Processing for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 48, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Art Processing', 'previous_stage': 'Template Processing', 'next_stage': 'Pre-editing', 'description': 'Stage Art Processing for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 49, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Pre-editing', 'previous_stage': 'Art Processing', 'next_stage': 'Non-XML Processing', 'description': 'Stage Pre-editing for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 50, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Non-XML Processing', 'previous_stage': 'Pre-editing', 'next_stage': 'Typesetting', 'description': 'Stage Non-XML Processing for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 51, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Typesetting', 'previous_stage': 'Non-XML Processing', 'next_stage': 'Proofreading', 'description': 'Stage Typesetting for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 52, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Proofreading', 'previous_stage': 'Typesetting', 'next_stage': 'Indexing', 'description': 'Stage Proofreading for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 53, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Indexing', 'previous_stage': 'Proofreading', 'next_stage': 'Corrections & 2P', 'description': 'Stage Indexing for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 54, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Corrections & 2P', 'previous_stage': 'Indexing', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Corrections & 2P for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 55, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Corrections & 2P', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 56, 'workflow_name': 'WF-05 Paging Only', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-05 Paging Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 57, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 58, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Template Processing', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 59, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'Template Processing', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Art Processing', 'description': 'Stage Template Processing for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 60, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'Art Processing', 'previous_stage': 'Template Processing', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Art Processing for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 61, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Art Processing', 'next_stage': 'Template Processing', 'description': 'Stage QC & Pre-flight for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 62, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'Template Processing', 'previous_stage': 'QC & Pre-flight', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Template Processing for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 63, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Template Processing', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 64, 'workflow_name': 'WF-06 Template Only', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-06 Template Only.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 65, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 66, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'XML Conversion', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 67, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'XML Conversion', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Template Processing', 'description': 'Stage XML Conversion for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 68, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'Template Processing', 'previous_stage': 'XML Conversion', 'next_stage': 'XML Conversion', 'description': 'Stage Template Processing for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 69, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'XML Conversion', 'previous_stage': 'Template Processing', 'next_stage': 'Art Processing', 'description': 'Stage XML Conversion for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 70, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'Art Processing', 'previous_stage': 'XML Conversion', 'next_stage': 'XML Conversion', 'description': 'Stage Art Processing for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 71, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'XML Conversion', 'previous_stage': 'Art Processing', 'next_stage': 'QC & Pre-flight', 'description': 'Stage XML Conversion for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 72, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'XML Conversion', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 73, 'workflow_name': 'WF-07 Digital Conversion', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-07 Digital Conversion.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 74, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 75, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Accessibility', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 76, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Accessibility', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Accessibility', 'description': 'Stage Accessibility for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 77, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Accessibility', 'previous_stage': 'Accessibility', 'next_stage': 'Art Processing', 'description': 'Stage Accessibility for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 78, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Art Processing', 'previous_stage': 'Accessibility', 'next_stage': 'Accessibility', 'description': 'Stage Art Processing for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 79, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Accessibility', 'previous_stage': 'Art Processing', 'next_stage': 'Accessibility QC', 'description': 'Stage Accessibility for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 80, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Accessibility QC', 'previous_stage': 'Accessibility', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Accessibility QC for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 81, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Accessibility QC', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 82, 'workflow_name': 'WF-08 Accessibility', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-08 Accessibility.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 83, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 84, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Editorial Assessment', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 85, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Editorial Assessment', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Template Processing', 'description': 'Stage Editorial Assessment for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 86, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Template Processing', 'previous_stage': 'Editorial Assessment', 'next_stage': 'Art Processing', 'description': 'Stage Template Processing for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 87, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Art Processing', 'previous_stage': 'Template Processing', 'next_stage': 'Pre-editing', 'description': 'Stage Art Processing for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 88, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Pre-editing', 'previous_stage': 'Art Processing', 'next_stage': 'Copyediting', 'description': 'Stage Pre-editing for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 89, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Copyediting', 'previous_stage': 'Pre-editing', 'next_stage': 'AQ Resolution', 'description': 'Stage Copyediting for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 90, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'AQ Resolution', 'previous_stage': 'Copyediting', 'next_stage': 'XML Conversion', 'description': 'Stage AQ Resolution for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 91, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'XML Conversion', 'previous_stage': 'AQ Resolution', 'next_stage': 'Typesetting', 'description': 'Stage XML Conversion for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 92, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Typesetting', 'previous_stage': 'XML Conversion', 'next_stage': 'Proofreading', 'description': 'Stage Typesetting for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 93, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Proofreading', 'previous_stage': 'Typesetting', 'next_stage': 'Indexing', 'description': 'Stage Proofreading for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 94, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Indexing', 'previous_stage': 'Proofreading', 'next_stage': 'Corrections & 2P', 'description': 'Stage Indexing for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 95, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Corrections & 2P', 'previous_stage': 'Indexing', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Corrections & 2P for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 96, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Corrections & 2P', 'next_stage': 'QC & Pre-flight', 'description': 'Stage QC & Pre-flight for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 97, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'QC & Pre-flight', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 98, 'workflow_name': 'WF-09 Fresh Book XML', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-09 Fresh Book XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},

        {'id': 99, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Job Initiation', 'previous_stage': None, 'next_stage': 'Manuscript Analysis', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 100, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Manuscript Analysis', 'previous_stage': 'Job Initiation', 'next_stage': 'Template Processing', 'description': 'Stage Job Initiation (Manuscript Analysis) for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 101, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Template Processing', 'previous_stage': 'Manuscript Analysis', 'next_stage': 'Art Processing', 'description': 'Stage Template Processing for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 102, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Art Processing', 'previous_stage': 'Template Processing', 'next_stage': 'Pre-editing', 'description': 'Stage Art Processing for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 103, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Pre-editing', 'previous_stage': 'Art Processing', 'next_stage': 'XML Conversion', 'description': 'Stage Pre-editing for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 104, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'XML Conversion', 'previous_stage': 'Pre-editing', 'next_stage': 'Typesetting', 'description': 'Stage XML Conversion for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 105, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Typesetting', 'previous_stage': 'XML Conversion', 'next_stage': 'Proofreading', 'description': 'Stage Typesetting for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 106, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Proofreading', 'previous_stage': 'Typesetting', 'next_stage': 'Indexing', 'description': 'Stage Proofreading for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 107, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Indexing', 'previous_stage': 'Proofreading', 'next_stage': 'Corrections & 2P', 'description': 'Stage Indexing for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 108, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Corrections & 2P', 'previous_stage': 'Indexing', 'next_stage': 'QC & Pre-flight', 'description': 'Stage Corrections & 2P for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 109, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'QC & Pre-flight', 'previous_stage': 'Corrections & 2P', 'next_stage': 'Delivery', 'description': 'Stage QC & Pre-flight for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
        {'id': 110, 'workflow_name': 'WF-10 Paging Only XML', 'stage_name': 'Delivery', 'previous_stage': 'QC & Pre-flight', 'next_stage': None, 'description': 'Stage Delivery for workflow WF-10 Paging Only XML.', 'active_status': True, 'created_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00'), 'updated_at': datetime.datetime.fromisoformat('2026-06-15T06:00:00+00:00')},
    ],

}


def seed():
    create_tables()
    db = SessionLocal()
    
    # Disable foreign keys for seeding to prevent circular reference errors (SQLite only)
    try:
        from sqlalchemy import text
        if db.bind.dialect.name == "sqlite":
            db.execute(text("PRAGMA foreign_keys = OFF;"))
    except Exception:
        pass

    # Clean existing data to allow safe rerun / refresh
    print("Cleaning existing database data...")
    for model_name, model_cls in reversed([
        ("RolesMaster", RolesMaster),
        ("StageMaster", StageMaster),
        ("User", User),
        ("Client", Client),
        ("Project", Project),
        ("ChapterInfo", ChapterInfo),
        ("File", File),
        ("FileVersion", FileVersion),
        ("ProjectStylesheet", ProjectStylesheet),
        ("StageDetail", StageDetail),
        ("WorkflowMaster", WorkflowMaster),
    ]):
        try:
            db.query(model_cls).delete()
            db.commit()
        except Exception as e:
            db.rollback()
            print(f"Error cleaning {model_name}: {e}")

    # Insert dumped data
    print("Seeding database...")
    for model_name, model_cls in [
        ("RolesMaster", RolesMaster),
        ("StageMaster", StageMaster),
        ("User", User),
        ("Client", Client),
        ("Project", Project),
        ("ChapterInfo", ChapterInfo),
        ("File", File),
        ("FileVersion", FileVersion),
        ("ProjectStylesheet", ProjectStylesheet),
        ("StageDetail", StageDetail),
        ("WorkflowMaster", WorkflowMaster),
    ]:
        rows = DUMPED_DATA.get(model_name, [])
        inserted = 0
        # Collect seeded chapter IDs to validate File.chapter_id foreign keys
        seeded_chapter_ids = {c['id'] for c in DUMPED_DATA.get('ChapterInfo', [])}
        for row in rows:
            if model_name == "User" and "password" in row:
                from app.domains.auth.security import hash_password
                row_copy = row.copy()
                row_copy["password_hash"] = hash_password(row_copy["password"])
                del row_copy["password"]
                instance = model_cls(**row_copy)
            elif model_name == "File":
                row_copy = row.copy()
                if row_copy.get("chapter_id") not in seeded_chapter_ids:
                    row_copy["chapter_id"] = None
                instance = model_cls(**row_copy)
            else:
                instance = model_cls(**row)
            db.add(instance)
            inserted += 1
        try:
            db.commit()
            print(f"  OK    Seeded {inserted} rows for {model_name}")
        except Exception as e:
            db.rollback()
            print(f"  ERROR Seeding {model_name}: {e}")

    # Re-enable foreign keys (SQLite only)
    try:
        from sqlalchemy import text
        if db.bind.dialect.name == "sqlite":
            db.execute(text("PRAGMA foreign_keys = ON;"))
    except Exception:
        pass

    # Reset primary key sequences for PostgreSQL to avoid duplicate key errors on future inserts
    try:
        if db.bind.dialect.name == "postgresql":
            from sqlalchemy import text
            print("Syncing PostgreSQL primary key sequences...")
            tables_to_sync = [
                ("users", "id"),
                ("clients", "id"),
                ("projects", "id"),
                ("project_stylesheets", "id"),
                ("roles_master", "id"),
                ("stage_master", "id"),
                ("stages_details", "id"),
                ("workflow_master", "id"),
                ("chapter_details", "id")
            ]
            for table, pk in tables_to_sync:
                db.execute(text(f"SELECT setval(pg_get_serial_sequence('{table}', '{pk}'), COALESCE(MAX({pk}), 1)) FROM {table};"))
            db.commit()
            print("PostgreSQL sequences synced successfully!")
    except Exception as e:
        db.rollback()
        print(f"Error syncing PostgreSQL sequences: {e}")
    
    db.close()
    print("Database seeding completed successfully!")

if __name__ == "__main__":
    seed()
