"""add conversion_started_at

Revision ID: 0018_add_conversion_started_at
Revises: 0017_add_qc_duration
Create Date: 2026-07-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0018_add_conversion_started_at'
down_revision: Union[str, Sequence[str], None] = '0017_add_qc_duration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('post_prod_chapters')]
    if 'conversion_started_at' not in columns:
        op.add_column('post_prod_chapters', sa.Column('conversion_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_prod_chapters', 'conversion_started_at')
    # ### end Alembic commands ###
