"""Add file_mappings to EvProject

Revision ID: 06c0e6203b07
Revises: 0026_add_source_file_id_to_files
Create Date: 2026-08-29 06:47:58.675485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0027_add_file_mappings_to_ev'
down_revision: Union[str, Sequence[str], None] = '0026_add_source_file_id_to_files'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if inspector.has_table('post_prod_ev_projects'):
        cols = {c['name'] for c in inspector.get_columns('post_prod_ev_projects')}
        if 'file_mappings' not in cols:
            op.add_column('post_prod_ev_projects', sa.Column('file_mappings', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_prod_ev_projects', 'file_mappings')
    # ### end Alembic commands ###
