"""Add XML Conversion models

Revision ID: 0033_add_xml_conversion_models
Revises: 0032_add_bod_models
Create Date: 2026-09-29 13:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '0040_add_xml_conversion_models'
down_revision: Union[str, Sequence[str], None] = '0038_journal_file_uploader'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = Inspector.from_engine(op.get_bind())
    tables = inspector.get_table_names()

    if 'post_prod_xmlConversion_projects' not in tables:
        op.create_table('post_prod_xmlConversion_projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_code', sa.String(), nullable=False),
        sa.Column('project_name', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('assignee', sa.String(), nullable=True),
        sa.Column('target_format', sa.String(), nullable=True),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('filepath', sa.String(), nullable=False),
        sa.Column('conversion_status', sa.String(), nullable=True),
        sa.Column('result_filepath', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_post_prod_xmlConversion_projects_client_code'), 'post_prod_xmlConversion_projects', ['client_code'], unique=False)
        op.create_index(op.f('ix_post_prod_xmlConversion_projects_id'), 'post_prod_xmlConversion_projects', ['id'], unique=False)
        op.create_index(op.f('ix_post_prod_xmlConversion_projects_project_name'), 'post_prod_xmlConversion_projects', ['project_name'], unique=False)

    if 'post_prod_xmlConversion_history' not in tables:
        op.create_table('post_prod_xmlConversion_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['post_prod_xmlConversion_projects.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_post_prod_xmlConversion_history_id'), 'post_prod_xmlConversion_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_prod_xmlConversion_history_id'), table_name='post_prod_xmlConversion_history')
    op.drop_table('post_prod_xmlConversion_history')
    op.drop_index(op.f('ix_post_prod_xmlConversion_projects_project_name'), table_name='post_prod_xmlConversion_projects')
    op.drop_index(op.f('ix_post_prod_xmlConversion_projects_id'), table_name='post_prod_xmlConversion_projects')
    op.drop_index(op.f('ix_post_prod_xmlConversion_projects_client_code'), table_name='post_prod_xmlConversion_projects')
    op.drop_table('post_prod_xmlConversion_projects')
    # ### end Alembic commands ###
