"""add_team_description_and_owner

Revision ID: 05c223313b8e
Revises: bffe6d2651da
Create Date: 2026-06-05 08:38:03.948846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_team_description_and_owner

Revision ID: 05c223313b8e
Revises: bffe6d2651da
Create Date: 2026-06-05 08:38:03.948846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05c223313b8e'
down_revision: Union[str, Sequence[str], None] = 'bffe6d2651da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'owner_id')
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
