"""add_wms_project_and_user_fields

Revision ID: 81589f971b92
Revises: 05c223313b8e
Create Date: 2026-06-06 07:57:53.963521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81589f971b92'
down_revision: Union[str, Sequence[str], None] = '05c223313b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('division_code', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('customer_contact', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('category', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('composition', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('project_manager', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('sales_person', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('edition', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('color', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('trim_size', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('copyright_year', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('manuscript_pages', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('estimated_pages', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('actual_pages', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('chapter_count_wms', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('isbn_no', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('billing_location', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('file_details', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('customer_access', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'customer_access')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'file_details')
    op.drop_column('projects', 'due_date')
    op.drop_column('projects', 'billing_location')
    op.drop_column('projects', 'isbn_no')
    op.drop_column('projects', 'chapter_count_wms')
    op.drop_column('projects', 'actual_pages')
    op.drop_column('projects', 'estimated_pages')
    op.drop_column('projects', 'manuscript_pages')
    op.drop_column('projects', 'copyright_year')
    op.drop_column('projects', 'trim_size')
    op.drop_column('projects', 'color')
    op.drop_column('projects', 'edition')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'sales_person')
    op.drop_column('projects', 'project_manager')
    op.drop_column('projects', 'composition')
    op.drop_column('projects', 'category')
    op.drop_column('projects', 'customer_contact')
    op.drop_column('projects', 'division_code')
    op.create_table('batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('use_markers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_jobs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_jobs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_jobs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('output_folder', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('batches_pkey')),
    sa.UniqueConstraint('batch_id', name=op.f('batches_batch_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('input_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('use_markers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), autoincrement=False, nullable=True),
    sa.Column('queue_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('output_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('review_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('json_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_paragraphs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auto_applied', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('needs_review', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_paragraph_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_paragraph_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('jobs_batch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey')),
    sa.UniqueConstraint('job_id', name=op.f('jobs_job_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
