"""add_cascades_and_indices

Revision ID: bffe6d2651da
Revises: wms_integration_001
Create Date: 2026-06-05 08:32:17.869286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'bffe6d2651da'
down_revision: Union[str, Sequence[str], None] = 'wms_integration_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    # Helper to get existing index names
    def index_exists(table_name, index_name):
        try:
            indices = [idx['name'] for idx in inspector.get_indexes(table_name)]
            return index_name in indices
        except:
            return False

    # Helper to get existing constraint names
    def constraint_exists(table_name, constraint_name):
        try:
            constraints = [c['name'] for c in inspector.get_foreign_keys(table_name)]
            return constraint_name in constraints
        except:
            return False

    # Chapters indices and constraints
    if not index_exists('chapters', 'ix_chapters_project_id'):
        op.create_index(op.f('ix_chapters_project_id'), 'chapters', ['project_id'], unique=False)

    try:
        op.drop_constraint(op.f('chapters_project_id_fkey'), 'chapters', type_='foreignkey')
    except:
        pass

    try:
        op.create_foreign_key(None, 'chapters', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    except:
        pass

    # File versions indices and constraints
    if not index_exists('file_versions', 'ix_file_versions_file_id'):
        op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    if not index_exists('file_versions', 'ix_file_versions_uploaded_by_id'):
        op.create_index(op.f('ix_file_versions_uploaded_by_id'), 'file_versions', ['uploaded_by_id'], unique=False)

    try:
        op.drop_constraint(op.f('file_versions_uploaded_by_id_fkey'), 'file_versions', type_='foreignkey')
    except:
        pass
    try:
        op.drop_constraint(op.f('file_versions_file_id_fkey'), 'file_versions', type_='foreignkey')
    except:
        pass

    try:
        op.create_foreign_key(None, 'file_versions', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    except:
        pass
    try:
        op.create_foreign_key(None, 'file_versions', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    except:
        pass

    # Files indices and constraints
    if not index_exists('files', 'ix_files_chapter_id'):
        op.create_index(op.f('ix_files_chapter_id'), 'files', ['chapter_id'], unique=False)
    if not index_exists('files', 'ix_files_checked_out_by_id'):
        op.create_index(op.f('ix_files_checked_out_by_id'), 'files', ['checked_out_by_id'], unique=False)
    if not index_exists('files', 'ix_files_project_id'):
        op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)

    try:
        op.drop_constraint(op.f('files_chapter_id_fkey'), 'files', type_='foreignkey')
    except:
        pass
    try:
        op.drop_constraint(op.f('files_checked_out_by_id_fkey'), 'files', type_='foreignkey')
    except:
        pass
    try:
        op.drop_constraint(op.f('files_project_id_fkey'), 'files', type_='foreignkey')
    except:
        pass

    try:
        op.create_foreign_key(None, 'files', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    except:
        pass
    try:
        op.create_foreign_key(None, 'files', 'users', ['checked_out_by_id'], ['id'], ondelete='SET NULL')
    except:
        pass
    try:
        op.create_foreign_key(None, 'files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    except:
        pass

    # Project stylesheets indices and constraints
    if not index_exists('project_stylesheets', 'ix_project_stylesheets_created_by_id'):
        op.create_index(op.f('ix_project_stylesheets_created_by_id'), 'project_stylesheets', ['created_by_id'], unique=False)

    try:
        op.drop_constraint(op.f('project_stylesheets_created_by_id_fkey'), 'project_stylesheets', type_='foreignkey')
    except:
        pass

    try:
        op.create_foreign_key(None, 'project_stylesheets', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_stylesheets', type_='foreignkey')
    op.create_foreign_key(op.f('project_stylesheets_created_by_id_fkey'), 'project_stylesheets', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_project_stylesheets_created_by_id'), table_name='project_stylesheets')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_project_id_fkey'), 'files', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('files_checked_out_by_id_fkey'), 'files', 'users', ['checked_out_by_id'], ['id'])
    op.create_foreign_key(op.f('files_chapter_id_fkey'), 'files', 'chapters', ['chapter_id'], ['id'])
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_index(op.f('ix_files_checked_out_by_id'), table_name='files')
    op.drop_index(op.f('ix_files_chapter_id'), table_name='files')
    op.drop_constraint(None, 'file_versions', type_='foreignkey')
    op.drop_constraint(None, 'file_versions', type_='foreignkey')
    op.create_foreign_key(op.f('file_versions_file_id_fkey'), 'file_versions', 'files', ['file_id'], ['id'])
    op.create_foreign_key(op.f('file_versions_uploaded_by_id_fkey'), 'file_versions', 'users', ['uploaded_by_id'], ['id'])
    op.drop_index(op.f('ix_file_versions_uploaded_by_id'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_project_id_fkey'), 'chapters', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_chapters_project_id'), table_name='chapters')
    # ### end Alembic commands ###
