"""add_cascades_and_indices

Revision ID: bffe6d2651da
Revises: wms_integration_001
Create Date: 2026-06-05 08:32:17.869286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bffe6d2651da'
down_revision: Union[str, Sequence[str], None] = 'wms_integration_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chapters_project_id'), 'chapters', ['project_id'], unique=False)
    op.drop_constraint(op.f('chapters_project_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_versions_uploaded_by_id'), 'file_versions', ['uploaded_by_id'], unique=False)
    op.drop_constraint(op.f('file_versions_uploaded_by_id_fkey'), 'file_versions', type_='foreignkey')
    op.drop_constraint(op.f('file_versions_file_id_fkey'), 'file_versions', type_='foreignkey')
    op.create_foreign_key(None, 'file_versions', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'file_versions', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_files_chapter_id'), 'files', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_files_checked_out_by_id'), 'files', ['checked_out_by_id'], unique=False)
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.drop_constraint(op.f('files_chapter_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_checked_out_by_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_project_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'files', 'users', ['checked_out_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_project_stylesheets_created_by_id'), 'project_stylesheets', ['created_by_id'], unique=False)
    op.drop_constraint(op.f('project_stylesheets_created_by_id_fkey'), 'project_stylesheets', type_='foreignkey')
    op.create_foreign_key(None, 'project_stylesheets', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_stylesheets', type_='foreignkey')
    op.create_foreign_key(op.f('project_stylesheets_created_by_id_fkey'), 'project_stylesheets', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_project_stylesheets_created_by_id'), table_name='project_stylesheets')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_project_id_fkey'), 'files', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('files_checked_out_by_id_fkey'), 'files', 'users', ['checked_out_by_id'], ['id'])
    op.create_foreign_key(op.f('files_chapter_id_fkey'), 'files', 'chapters', ['chapter_id'], ['id'])
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_index(op.f('ix_files_checked_out_by_id'), table_name='files')
    op.drop_index(op.f('ix_files_chapter_id'), table_name='files')
    op.drop_constraint(None, 'file_versions', type_='foreignkey')
    op.drop_constraint(None, 'file_versions', type_='foreignkey')
    op.create_foreign_key(op.f('file_versions_file_id_fkey'), 'file_versions', 'files', ['file_id'], ['id'])
    op.create_foreign_key(op.f('file_versions_uploaded_by_id_fkey'), 'file_versions', 'users', ['uploaded_by_id'], ['id'])
    op.drop_index(op.f('ix_file_versions_uploaded_by_id'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_project_id_fkey'), 'chapters', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_chapters_project_id'), table_name='chapters')
    # ### end Alembic commands ###
