from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, DateTime, Date, JSON, Enum as SQLEnum, TypeDecorator, BigInteger, Text, func
from sqlalchemy.dialects.postgresql import ARRAY as PG_ARRAY, JSONB
from sqlalchemy.orm import relationship, synonym
from datetime import datetime
from app.database import Base
import enum

class DialectArray(TypeDecorator):
    impl = JSON
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_ARRAY(String))
        return dialect.type_descriptor(JSON)

class WorkflowStatus(str, enum.Enum):
    Planning = "Planning"
    Inprogress = "In-progress"
    XML_GENERATED = "XML_GENERATED"
    Published = "Published"

from app.domains.auth.models import User, CompatibilityRoleItem, CompatibilityRolesList

class File(Base):
    __tablename__ = "files"
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    chapter_id = Column(BigInteger, ForeignKey("chapter_details.id", ondelete="CASCADE"), nullable=True, index=True)
    filename = Column(String, index=True)
    file_type = Column(String)
    category = Column(String, default="Manuscript") # Art, Manuscript, InDesign, Proof, XML
    path = Column(String)
    uploaded_at = Column(DateTime, default=datetime.utcnow)
    version = Column(Integer, default=1)
    
    project = relationship("Project", back_populates="files")
    chapter = relationship("ChapterInfo", back_populates="files")
    
    # Checkout Logic
    is_checked_out = Column(Boolean, default=False)
    checked_out_by_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    checked_out_at = Column(DateTime, nullable=True)
    
    checked_out_by = relationship("User", foreign_keys=[checked_out_by_id])
    versions = relationship("FileVersion", back_populates="original_file", cascade="all, delete-orphan")


class FileVersion(Base):
    __tablename__ = "file_versions"
    id = Column(Integer, primary_key=True, index=True)
    file_id = Column(Integer, ForeignKey("files.id", ondelete="CASCADE"), index=True)
    version_num = Column(Integer)
    path = Column(String)
    uploaded_at = Column(DateTime, default=datetime.utcnow)
    uploaded_by_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)

    original_file = relationship("File", back_populates="versions")
    uploaded_by = relationship("User")


class Comment(Base):
    __tablename__ = "comments"
    id = Column(Integer, primary_key=True, index=True)
    file_id = Column(Integer, ForeignKey("files.id", ondelete="CASCADE"), nullable=False, index=True)
    # UUID generated by the editor; stable across renames; what appears in `data-comment-id`
    # spans inside saved HTML. Unique per file.
    comment_uuid = Column(String(64), nullable=False, index=True)
    text = Column(Text, nullable=False, default="")
    author_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    # Snapshot at creation time so the display name survives author deletion / rename.
    author_name = Column(String(150), nullable=False, default="")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    resolved = Column(Boolean, default=False, nullable=False)

    file = relationship("File")
    author = relationship("User")


class WebDAVLock(Base):
    __tablename__ = "webdav_locks"
    id = Column(Integer, primary_key=True, index=True)
    file_id = Column(Integer, ForeignKey("files.id", ondelete="CASCADE"), nullable=False, index=True)
    lock_token = Column(String(200), unique=True, nullable=False, index=True)
    owner_user_id = Column(BigInteger, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    expires_at = Column(DateTime(timezone=True), nullable=True)
    last_refresh_at = Column(DateTime(timezone=True), nullable=True, server_default=func.now(), onupdate=func.now())
    user_agent = Column(String(512), nullable=True)
    remote_addr = Column(String(128), nullable=True)

    file = relationship("File")
    owner = relationship("User")

# Import all other domain models to register them in Base.metadata for foreign keys
from app.domains.clients.models import Client  # noqa: F401
from app.domains.workflow.models import (  # noqa: F401
    RolesMaster,
    StageActivityMaster,
    StageMaster,
    StageDetail,
    WorkflowMaster,
    ChapterInfo,
)

Chapter = ChapterInfo




